In [ ]:
#palindrome
a = input()
b = a[::-1]
if a == b:
  print('palindrome')
else:
    print('not palindrome')

KeyboardInterrupt: Interrupted by user

In [ ]:
#factorial
a = int(input())
fact = 1
for i in range(1,a+1):
  fact*=i
print('factorial:',fact)

8
factorial: 40320

In [ ]:
#largest number
a = int(input())
b = int(input())
print(max(a,b))

2
6
6

In [ ]:
#armstrong
a = int(input())
t = a
b = len(str(t))
sum = 0
while t>0:
  d = t%10
  sum += d**b
  t = t//10
if(sum == a):
  print('armstrong')
else:
  print('not armstrong')

153
armstrong

In [ ]:
#celtofahr
c = float(input("enter temperature in celcius:"))

f = (c *9/5) + 32

print("fahrenheit =", f)

enter temperature in celcius:100
fahrenheit = 212.0

In [ ]:
#prime number
for n in range(1,51):
 if n>1:
  for i in range(2,n):
    if n%i == 0:
     break
  else:
      print(n, end=" ")

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47

In [ ]:
#swap
a = input()
b = input()
temp = a
a = b
b = temp
print(a)
print(b)

bob
alex
alex
bob

In [ ]:
#fibonacci
n = int(input())
sum = 0
a, b = 0, 1
for i in range(n):
  print(a, end="")
  a, b = b , a + b

9
01123581321

In [ ]:
#avg
a = int(input())
b = int(input())
c = int(input())
avg = (a+b+c)//3
print(avg)

1
2
5
2

In [ ]:
#vowels using slice
a = "butterfly"
vowels = a[1] + a[4]
print(vowels)

ue

In [ ]:
#vowels without slice
text = input()
vowels = "aeiouAEIOU"
count = 0
for ch in text:
  if ch in vowels:
    count += 1
    print(ch)
print(count)

butterfly
u
e
2

In [ ]:
a = int(input())
b = int(input())

x = a
y = b

while y != 0:
    x, y = y, x % y

gcd = x
lcm = (a * b) // gcd

print("GCD =", gcd)
print("LCM =", lcm)

12
18
GCD = 6
LCM = 36

In [ ]:
a = [3,17,29,7,65,92,]
print(max(a),min(a))

92 3

In [ ]:
def add(a,b):
  return a +b
def sub(a,b):
  return a-b
def mul(a,b):
  return a*b
def div(a,b):
  return a/b
add(5,6)

11

In [ ]:
n = 75
if (n>0):
  print("positive number")
elif("n<0"):
  print("negative number")
else:
  print(0)

positive number

In [ ]:
n = int(input())
if n%4 == 0:
  print("leap year ")
else:
  print("normal")

2030
normal

In [ ]:
a = int(input())
if a%2 == 0 :
  print("even")
else:
  print("odd")

5
odd

In [ ]:
a = input()
b = input()
if sorted(a) == sorted(b):
  print('anagram')
else:
  print('not anagram')

silent
listen
anagram

In [ ]:
for i in range(1,6):
  for j in range(1,i+1):
    print(j,end="" )
  print()

1
12
123
1234
12345

In [ ]:
a = int(input())
for i in range(1,a+1):
    print("*"*i)

5
*
**
***
****
*****

In [ ]:
a = int(input())
for i in range(a):
  print(" "*i+"*"*(a-i))

5
*****
 ****
  ***
   **
    *

In [ ]:
a = int(input())
for i in range(1,a+1):
  print(" "*(a-i)+"* "*i)
for i in range(a-1,0,-1):
  print(" "*(a-i)+"* "*i)

3
  *
 * *
* * *
 * *
  *

In [ ]:
a = int(input())
for i in range(1,a+1):
  print(" "*(a-i)+"* "*i)

5
    *
   * *
  * * *
 * * * *
* * * * *

In [ ]:
#first 3 largest numbers
a = [20,40,80,70,60,30]
largest = sorted(a, reverse=True)[:3]
print("numbers:", largest)

numbers: [80, 70, 60]

In [ ]:
#anagram without using sorted
a = input()
b = input()
if(a==b,b==a):
  print("anagram")
else:
  print("not anagram")

listen
silent
anagram

In [ ]:
#power of 2
import math
a = int(input())
if math.sqrt(a):
  print("power of 2")
else:
  print("not")

8
power of 2

In [ ]:
a =  input()
b = input()
c = 0

for i in range(len(a)):
  if a[i]!=b[i]:
    c+=1
  if c==1:
   print("yes")
else:
  print("no")

cat
cape
yes
no

In [ ]:
a = input()
l ="  "
for i in  range(len(a)):
  c =" "
  for j in range(i,len(l)):
    if a[j] not in c:
      c+=a[j]
    else:
      break
    if (len(c)>len(l)):
      l=c
    print(len(l))

abcabcbb
2
3
3
3
3

In [ ]:
n = int(input())
x = list(map(int,input().split()))
for i in range  (1,n):
   if(x[i]==0):
    d = x[i-1]+1
    print(d)
    break

5
1 2 0 4 5
3

In [ ]:
st = input()
st1 = list(st.lower())
vowels = ['a', 'e', 'i', 'o', 'u']
vlist = []
r = 0
for i in st1:
    if i in vowels:
        vlist.append(i)
vlist.reverse()
for i in range(len(st1)):
    if st1[i] in vowels:
        st1[i] = vlist[r]
        r += 1
print("".join(st1))

education
odicatuen

In [ ]:
s = input()
longest = ""
for i in range(len(s)):
    for j in range(i + 1, len(s) + 1):
        sub = s[i:j]
        if sub == sub[::-1] and len(sub) > len(longest):
            longest = sub
print(len(longest))

abcabcbb
3

In [ ]:
class student:
  def __init__(self,name,age):
    self.name = name
    self.age = age
  def display(self):
      print("name:",self.name)
      print("age:",self.age)

obj = student("vish",3)
obj.display()

name: vish
age: 3

In [ ]:
class father:
  def bike(self):
    print("father has a bike")
class son(father):
  def cycle(self):
    print("son has cycle")
obj = son()
obj.bike()

father has a bike

In [ ]:
class father:
  def property(self):
    print("father's property")
class son(father):
  pass
obj = son()
obj.property()

father's property

In [ ]:
class animal:
  def sound(self):
    print("animal makes sound")

In [ ]:
class bank:
  def __init__(self):
    self.balance = 5000
  def show_balance(self):
     print("balance:",self.balance)
obj = bank()
obj.show_balance()

balance: 5000

In [ ]:
class multiply:
  def product(self,a = None , b =None , c = None):
    if a and b and c:
      print("product=",a*b*c)
    elif a and b:
      print("product=", a*b)
obj = multiply()
obj.product(2,3)
obj.product(2,3,4)

product= 6
product= 24

In [ ]:
n = int(input())
b = int(str(n)[::-1])
for i in range(2,b):
  if b%i == 0:
    print("not prime")
    break
else:
    print("prime")

5
prime

In [ ]:
#adam number
n= int(input())
sq = n ** 2
rev= int(str(n)[::-1])
sqrev= rev** 2
revsq = int(str(sq)[::-1])
if sqrev== revsq:
    print("Adam")
else:
    print("NOT Adam")

12
Adam

In [ ]:
#circular prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True
def is_circular_prime(n):
    s = str(n)
    for i in range(len(s)):
        r = int(s[i:] + s[:i])
        if not is_prime(r):
            return False
    return True
n = int(input())
if is_circular_prime(n):
    print("Circular Prime")
else:
    print("Not Circular Prime")

197
Circular Prime

In [ ]:
x = 5
y = 3
z = 2
result = x + y * z // y
print(result)

7

In [1]:
import os
os.environ['KAGGLE_USERNAME']='arihantsharmakk'
os.environ['KAGGLE_KEY'] = 'KGAT_088c38bd49e7d3fa79ddf517f2cd03bd'

!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.5.20)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.5.1)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.10.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)

In [2]:
!kaggle datasets download -d 'yasserh/titanic-dataset'

Dataset URL: https://www.kaggle.com/datasets/yasserh/titanic-dataset
License(s): CC0-1.0
Downloading titanic-dataset.zip to /content
100% 22.0k/22.0k [00:00<00:00, 31.2MB/s]

In [4]:
!unzip titanic-dataset.zip

Archive:  titanic-dataset.zip
  inflating: Titanic-Dataset.csv

In [3]:
import pandas as pd
df = pd.read_csv("titanic-dataset.zip")
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [5]:
print(len(df))
print(df.shape)

891
(891, 12)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [10]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [11]:
df.drop

<bound method DataFrame.drop of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [12]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [13]:
df["Age"].fillna(df["Age"].median(),inplace=True)
print(df[["Age"]].head(10))
print(df[["Age"]].isnull().sum())

    Age
0  22.0
1  38.0
2  26.0
3  35.0
4  35.0
5  28.0
6  54.0
7   2.0
8  27.0
9  14.0
Age    0
dtype: int64

/tmp/ipykernel_1315/4088595300.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(),inplace=True)

In [14]:
df.drop_duplicates(inplace=True)
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female  28.0      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [15]:

x=df.drop(['Survived'],axis=1)
y=df['Survived']
print(x)
print(y)

     PassengerId  Pclass                                               Name  \
0              1       3                            Braund, Mr. Owen Harris
1              2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2              3       3                             Heikkinen, Miss. Laina
3              4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4              5       3                           Allen, Mr. William Henry
..           ...     ...                                                ...
886          887       2                              Montvila, Rev. Juozas
887          888       1                       Graham, Miss. Margaret Edith
888          889       3           Johnston, Miss. Catherine Helen "Carrie"
889          890       1                              Behr, Mr. Karl Howell
890          891       3                                Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S
1    female  38.0      1      0          PC 17599  71.2833   C85        C
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
3    female  35.0      1      0            113803  53.1000  C123        S
4      male  35.0      0      0            373450   8.0500   NaN        S
..      ...   ...    ...    ...               ...      ...   ...      ...
886    male  27.0      0      0            211536  13.0000   NaN        S
887  female  19.0      0      0            112053  30.0000   B42        S
888  female  28.0      1      2        W./C. 6607  23.4500   NaN        S
889    male  26.0      0      0            111369  30.0000  C148        C
890    male  32.0      0      0            370376   7.7500   NaN        Q

[891 rows x 11 columns]
0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [16]:
df['Sex'] = df['Sex'].map({'male':0,'female':1})
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    0  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1
2                               Heikkinen, Miss. Laina    1  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1
4                             Allen, Mr. William Henry    0  35.0      0
..                                                 ...  ...   ...    ...
886                              Montvila, Rev. Juozas    0  27.0      0
887                       Graham, Miss. Margaret Edith    1  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"    1  28.0      1
889                              Behr, Mr. Karl Howell    0  26.0      0
890                                Dooley, Mr. Patrick    0  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [17]:
df.drop('Cabin' , axis=1 , inplace=True)

In [18]:
df['Embarked']=df['Embarked'].fillna(df['Embarked'].mode()[0])

In [19]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import pandas as pd

x=df.drop(['Survived','Name', 'Ticket'],axis=1)
y=df['Survived']

x = pd.get_dummies(x, columns=['Embarked'], drop_first=True)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=LogisticRegression(max_iter=1000)
model.fit(x_train, y_train)
print("Model Trained")

y_pred=model.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
cm=confusion_matrix(y_test,y_pred)
report=classification_report(y_test,y_pred)
print("Accuracy:",accuracy)
print("Confusion Matrix:",cm)
print("Classification Report:",report)

Model Trained
Accuracy: 0.8044692737430168
Confusion Matrix: [[89 16]
 [19 55]]
Classification Report:               precision    recall  f1-score   support

           0       0.82      0.85      0.84       105
           1       0.77      0.74      0.76        74

    accuracy                           0.80       179
   macro avg       0.80      0.80      0.80       179
weighted avg       0.80      0.80      0.80       179

In [ ]:
a = input()
b = input()
if len(sorted(a)) == len(sorted(b)):
  print("equivalent")
else:
  print('not equivalent')

mobile laptop watch mobile
watch mobile laptop mobile
equivalent

In [ ]:
a = [12, 45, 67, 23, 89, 67]
first=second=-1
for num in a:
  if(num>first):
    second=first
    first= num
  elif(num>second):
    second=num
print(second)

67

In [ ]:
df['HasCabin'] = df['Cabin'].notnull().astype(int)

print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0
2                             Heikkinen, Miss. Laina    1  26.0      0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0
4                           Allen, Mr. William Henry    0  35.0      0      0

             Ticket     Fare Cabin Embarked  HasCabin
0         A/5 21171   7.2500   NaN        S         0
1          PC 17599  71.2833   C85        C         1
2  STON/O2. 3101282   7.9250   NaN        S         0
3            113803  53.1000  C123        S         1
4            373450   8.0500   NaN        S         0

In [ ]:
print(df['Embarked'].unique())

['S' 'C' 'Q']

In [ ]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

df['Embarked'] = df['Embarked'].map({
    'S': 0,
    'C': 1,
    'Q': 2
})

print(df[['Embarked']].head())

   Embarked
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN

In [ ]:
s = "swiss"
for ch in s :
  if s.count(ch)==1:
    print("firstcharracter",ch)
    break

firstcharracter w

In [ ]:
n = list(map(int,input().split()))
odd = []
even = []
for num in n:
  if num%2!=0:
    odd.append(num)
  else:
    even.append(num)
earranged_num = even + odd

print(earranged_num)

 7 8 9 6 4 3
[8, 6, 4, 7, 9, 3]

In [ ]:
a = list(input().split())
k = 2
result = a[-k:]+a[:-k]
print(result)

1 2 3 4 5
['4', '5', '1', '2', '3']

In [ ]:
a = [2,7,11,15,3,6]
t = 9
for i in range(len(a)):
   for j in range(i+1,len(arr)):
    if arr[i]+ arr[j] == t:
      print(arr[i],arr[j])

2 7
3 6

In [ ]:
n = list(map(int,input().split()))
even = 0
odd = 0
for i in range(len(n)):
  if (i%2 == 0):
    even+=n[i]
  else:
    odd+=n[i]
print(even-odd)

1 2 3 4 5
3

In [ ]:
import ast

KeyboardInterrupt: Interrupted by user